### PR TITLE
Rewrite in Rust

### LINKED ISSUE #59: [Bug]: Unicode symbols incorrectly parsed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My input for `Copyright`:  `Copyright © 2022`
What was written to the manifest: `Copyright \0 2022`
image

### LINKED ISSUE #110: [Bug]: Issues in non-Windows platforms
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Here's a checklist:
- [x] Incorrect detection of MSI values
<details>

<summary>Details (original comment)</summary>

Inside WSL:
image

The product code is incorrect, and the `InstallerType` is also replaced from `wix` to `msi`. Here is the correct entry, as shown in Windows. It even has some additional entries:
image

</details>

- [ ] Komac does not remember/save the entered token

### LINKED ISSUE #217: [Feature/Idea]: The DMG created with jpackage does not include apple silicon support
### What would you like to see changed/added?

Trying to run it after install starts the rosetta install prompt, where it can already be run natively with just the jar.

### LINKED ISSUE #294: [Bug]: MalformedInputException
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Using komac version 1.10.1 installed via winget.

Got the following exception.
image

Could continue as normal after pressing enter.

<details>
<summary>Log</summary>
C:\Users\michi\development\private\winget-pkgs>komac new
Please enter your GitHub personal access token:

[Required] Enter the package identifier
Example: Microsoft.Excel
Package Identifier: Shemnei.punktf

[Required] Enter the package version
Example: 3.88.2
Package Version: 3.0.0

[Required] Enter the Download URL to the installer
Installer URL: https://github.com/Shemnei/punktf/releases/download/v3.0.0/punktf-x86_64-pc-windows-msvc.zip

[Required] Select the nested installer type
[ ] EXE
[x] PORTABLE
[Optional] Enter the command line alias to be used for calling the package
Installer: /punktf-x86_64-pc-windows-msvc/punktf.exe
Portable Command Alias: punktf

[Optional] Enter the custom installer switch
Example: /norestart, -norestart
Custom installer switch:

[Optional] Enter the installer locale
Example: bi-PF
Installer locale: en-US

[Optional] Enter the upgrade behaviour
[x] Install
[ ] UninstallPrevious

Do you want to create another installer?
[ ] Yes
[x] NoException in thread "DefaultDispatcher-worker-1" io.ktor.utils.io.charsets.MalformedInputException: Input length = 1
        at io.ktor.utils.io.charsets.CharsetJVMKt.throwExceptionWrapped(CharsetJVM.kt:370)
        at io.ktor.utils.io.charsets.CharsetJVMKt.decode(CharsetJVM.kt:241)
        at io.ktor.utils.io.charsets.EncodingKt.decode(Encoding.kt:103)
        at io.ktor.utils.io.charsets.EncodingKt.decode$default(Encoding.kt:101)
        at io.ktor.client.statement.HttpResponseKt.bodyAsText(HttpResponse.kt:89)
        at io.ktor.client.statement.HttpResponseKt.bodyAsText$default(HttpResponse.kt:84)
        at github.GitHubDetection.findSha256(GitHubDetection.kt:107)
        at github.GitHubDetection.access$findSha256(GitHubDetection.kt:23)
        at github.GitHubDetection$findSha256$1.invokeSuspend(GitHubDetection.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@69[ ] Yes
[x] No

</details>

### LINKED ISSUE #308: [Feature/Idea]: Add a command for outputting the manifest locally
### What would you like to see changed/added?

I've looked at the doco and can't seem to figure out if this already exists. If not it would be great if we could pass a directory using a command.

### LINKED ISSUE #309: [Feature/Idea]: Signing commits
### What would you like to see changed/added?

Add parameters `--key` and `--key-path` which read GPG keys from string and a path to a file containing a key respectively, and use them to create signed commits.

Also, throw error if validate that both flags are passed together.

### LINKED ISSUE #318: Use Gradle Toolchain to pin JDK version
While poking around the project I noticed that the `build.gradle.kts` declares the the Java compatibility but doesn't enforce a consistent JVM environment.

Gradle offers [Toolchains](https://docs.gradle.org/current/userguide/toolchains.html) to ensure that projects can be build correctly with the expected JVM compile environment.

> In order to improve reproducibility of the builds and make build requirements clearer, Gradle allows configuring toolchains on both project and task levels.

Unless there are specific reasons that I fail to see I would suggest adding such a declaration to make working with the project source code a little more robust.

---

Addendum: I would also suggest switching away from `sourceCompatibility`/`targetCompatibility` to [`release`](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:compiling_with_release) instead.

### LINKED ISSUE #319: Rust rewrite
### Summary
I am rewriting Komac in Rust.

### Why are you rewriting Komac in Rust?
I love Kotlin as a language but it suffers from high memory usage and either requires me to bundle the Java Runtime Environment into an installer or have the user already have Java installed and then run a JAR. Kotlin/Native exists but I have to implement logic for each source set where I need to and most Kotlin libraries aren't fully multiplatform yet. Even if Kotlin/Native had a perfect ecosystem, Rust does not have a garbage collector, so there's no overhead there like there is in Kotlin/Native. 

One of the biggest things in Komac currently is reading MSIs etc using native Windows APIs. I have to write lots of Java Native Access code in order to do so.

There's also a lot of things where I've had to implement something from scratch myself where in Rust, there is a crate that does it all for me. E.g. the interactive menus in Komac aren't amazingly versatile. In Rust, I'd use [inquire](https://github.com/mikaelmello/inquire).

### What are the benefits of rewriting Komac in Rust?
- Easier to maintain
- Native executable (e.g. exe for Windows)
- Smaller binary/installer
- Better performance
- **Much** less memory usage

### What does this mean for me?
In the future, you'll have a native executable for your platform and it'll be faster :)
Alongside this, the things that weren't able to be implemented in Komac like secure token storage for Linux and macOS will be in rumac. rumac will also use GitHub's GraphQL API over the REST API which can make getting data from GitHub faster (several REST API calls can be written into one GraphQL query). Additionally, commits created with rumac will be verified as commits created through the GraphQL API are automatically signed by GitHub and marked as verified.

### Progress of Rust rewrite
- [x] New Package command
- [x] Update Command
- [x] Remove Version command
- [x] Cleanup command
- [x] Adding token to platform's secure storage
   - Komac only had this implemented for Windows. rumac has it for all platforms.
- [x] Get values from MSI
   - Komac relied on Msi.dll on Windows or LibMsi on Linux/macOS. rumac uses [rust-msi](https://github.com/mdsteele/rust-msi) to implement this cross-platform.
- [x] Get values from Msix and MsixBundle files
   - [x] Deserialise manifest from XML
   - [x] SignatureSha256
   - [x] [Package Family Name](https://marcinotorowski.com/2021/12/19/calculating-hash-part-of-msix-package-family-name)
- [ ] Get values from ZIP
- [x] Get metadata from GitHub repository from URL
- [x] Interactive menus
- [x] File downloading with progress
- [x] Get architecture of exe
- [x] Check exe is inno, burn, nullsoft, etc
- [x] Version comparison (Knowing which version in a list of versions is the latest one)

### LINKED ISSUE #327: [Bug]: Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property bestMatch has not been initialized
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```console
> Komac update --id ViGEm.ViGEmBus --version 1.22.0 --urls https://github.com/nefarius/ViGEmBus/releases/download/v1.22.0/ViGEmBus_1.22.0_x64_x86_arm64.exe
Latest version of ViGEm.ViGEmBus: 1.21.442
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property bestMatch has not been initialized
        at utils.UrlsToInstallerMatcher.matchInstallers(UrlsToInstallerMatcher.kt:54)
        at commands.QuickUpdate.loopParameterUrls(QuickUpdate.kt:265)
        at commands.QuickUpdate.access$loopParameterUrls(QuickUpdate.kt:49)
        at commands.QuickUpdate$loopParameterUrls$1.invokeSuspend(QuickUpdate.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at commands.QuickUpdate.run(QuickUpdate.kt:105)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:306)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:319)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:458)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:455)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:475)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:482)
        at MainKt.main(Main.kt:24)
Failed to launch JVM
```

### LINKED ISSUE #353: [Bug]: Failed to delete downloaded temp file
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```console
> Komac new
[Required] Enter the package identifier
Example: Microsoft.Excel
Package Identifier: Gyan.FFmpeg.Essentials

[Required] Enter the package version
Example: 7.49.1
Package Version: 6.1

[Required] Enter the Download URL to the installer
Installer URL: https://github.com/GyanD/codexffmpeg/releases/download/6.1/ffmpeg-6.1-essentials_build.zip

[Required] Select files to use
[x] /ffmpeg-6.1-essentials_build/bin/ffmpeg.exe
[x] /ffmpeg-6.1-essentials_build/bin/ffplay.exe
[x] /ffmpeg-6.1-essentials_build/bin/ffprobe.exe
[Confirm]
[Required] Select the nested installer type
[ ] EXE
[x] PORTABLE
[Optional] Enter the command line alias to be used for calling the package
Installer: ffmpeg.exe
Portable Command Alias:

[Optional] Enter the command line alias to be used for calling the package
Installer: ffplay.exe
Portable Command Alias:

[Optional] Enter the command line alias to be used for calling the package
Installer: ffprobe.exe
Portable Command Alias:

Exception in thread "main" java.io.IOException: failed to delete C:\Users\rycae\AppData\Local\Temp\Gyan.FFmpeg.Essentials 6.1 - 2023.12.15-15.46.13.zip
        at okio.JvmSystemFileSystem.delete(JvmSystemFileSystem.kt:137)
        at okio.FileSystem.delete(FileSystem.kt:115)
        at network.Downloader.download(Downloader.kt:67)
        at network.Downloader$download$1.invokeSuspend(Downloader.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at commands.NewManifest.run(NewManifest.kt:101)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:306)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:319)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:458)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:455)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:475)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:482)
        at MainKt.main(Main.kt:24)
Exception in thread "Thread-10" java.io.IOException: failed to delete C:\Users\rycae\AppData\Local\Temp\Gyan.FFmpeg.Essentials 6.1 - 2023.12.15-15.46.13.zip
        at okio.JvmSystemFileSystem.delete(JvmSystemFileSystem.kt:137)
        at okio.FileSystem.delete(FileSystem.kt:115)
        at network.Downloader.downloadFile$lambda$4$lambda$3(Downloader.kt:89)
        at java.base/java.lang.Thread.run(Unknown Source)
Failed to launch JVM
```

Posting an issue here for reference, but I guess this won't be relevant on the rust rewrite.

### PR DESCRIPTION
**Pull request by russellbanks**
There is significantly less code compared to the Kotlin codebase, but around ~68k of the lines is the GitHub GraphQL schema required for making calls to GitHub via the GraphQL API.

- Resolves #59
- Resolves #110
- Resolves #217
- Resolves #294
- Resolves #308
- Resolves #309
- Resolves #318
- Closes #319
- Resolves #327
- Resolves #353

I haven't done any proper benchmarks but in terms of memory usage, Komac tends to use about 2-5mb on memory, compared to the potentially hundreds that Komac could use becuse of the garbage collector, etc.

In rust, code can be compiled for speed or binary size. Komac is compiled for speed. Despite this, the resulting binary is about 7-8mb on Windows.

### Windows and macOS
Komac uses [native-tls](https://crates.io/crates/native-tls) on Windows and macOS, which uses SChannel and Secure Transport respectively, which are the platform's native implementations.

### Linux
On Linux, Komac could use OpenSSL. However, this would require it to be installed on the user's system. Instead, Komac uses [rustls](https://crates.io/crates/rustls), which has [shown itself](https://www.zdnet.com/article/a-rust-based-tls-library-outperformed-openssl-in-almost-every-category/) to be more performant than OpenSSL anyway. This adds about ~600kb to the resulting binary, but means that nothing additional needs to be installed on the user's system.

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
Also resolves:
- https://github.com/russellbanks/Komac/issues/318
- https://github.com/russellbanks/Komac/issues/308

**Comment by sitiom** [comment]
> Also resolves:
> 
> * https://github.com/russellbanks/Komac/issues/318
> * https://github.com/russellbanks/Komac/issues/308

Also https://github.com/russellbanks/Komac/issues/309?

Also, will the naming change to Rumac or will it remain as Komac 😅

**Comment by vedantmgoyal2009** [comment]
Previously, we had decided to change it to Rumac, but then it would confuse while referring to the tool since many people are already familiar with the old name "Komac". However, the full form would change:

| Previous | Now |
| :-: | :-: |
| **Ko**tlin **Ma**nifest **C**reater for WinGet | **Ko**mmunity **Ma**nifest **C**reater for WinGet |

I think this gentle twist with the spelling of "community" is good since it gives a feeling of a community of contributors to winget-pkgs/open-source/komac itself.

**Comment by sitiom** [comment]
I was also thinking of the double meaning of Rumac: **Russell's/Rust** Manifest Creator 😅

**Comment by russellbanks** [comment]
> Also, will the naming change to Rumac or will it remain as Komac 😅

I've been back and forth with this quite a bit but I think seeing as Komac has been used for a while, changing it could cause confusion, and would actually be quite a lot to change. I guess the 'Ko' part just won't refer to it being written in Kotlin.

**Comment by russellbanks** [comment]
There are still a few things that aren't finished in this rewrite, but plenty for a beta release. I've been using this rewrite for updating packages myself and having it in this repository will be more transparent.

**Comment by vedantmgoyal2009** [comment]
* #353

**Pull request merged**
