### PR TITLE
fix: set display version in manifest as package version

### PR DESCRIPTION
**Pull request by iamdejan**
# Problem

I encountered [error](https://github.com/microsoft/winget-pkgs/pull/112570/checks?check_run_id=15166049103) when upgrading Arduino IDE package. The error says:
`Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index.Existing DisplayVersion range in index :  [ [2.1.0, 2.1.0]]`

After I checked `Komac`'s source code, I found out that the `displayVersion` refers to MSI file if included. That shouldn't be a problem. However, one edge case is that the data contained in MSI file is wrong.

# Steps to Reproduce

Since I encountered this bug with Arduino IDE installer, the package and URL will be of Arduino IDE.
1) Run this command: `komac update --id ArduinoSA.IDE.stable --version 2.1.1 --urls https://github.com/arduino/arduino-ide/releases/download/2.1.1/arduino-ide_2.1.1_Windows_64bit.msi`
    a) This command must be run before [this PR](https://github.com/microsoft/winget-pkgs/pull/112570) is merged.
2) Save the manifest.
3) Search for `DisplayVersion` in the `*.installer.yaml` file. Notice that the version is not the same as version sent in command line.

# My Solution

My solution is to set `displayVersion` as package version, regardless of whether the installer is MSI file or not.

### CODE REVIEW

**Comment by iamdejan** [comment]
Hi @russellbanks , any update? Or do you think that this is not needed since it's edge case?

**Comment by vedantmgoyal2009** [comment]
* https://github.com/vedantmgoyal2009/winget-releaser/issues/174

**Comment by vedantmgoyal2009** [comment]
@iamdejan the MSI didn't contain the wrong version, it is a bug in Komac. See my PR https://github.com/russellbanks/Komac/pull/264 for more info.

**Comment by vedantmgoyal2009** [comment]
@iamdejan the MSI didn't contain the wrong version, it is a bug in Komac. See my PR https://github.com/russellbanks/Komac/pull/264 for more info.

Hence, this PR doesn't fix the original issue, and some refactoring will be needed to fix the problem from its root cause.

**Pull request closed without merging**
